import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
import datetime
import uuid
from google.oauth2 import service_account
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

SERVICE_ACCOUNT_FILE = os.path.join(os.path.dirname(__file__), 'service_account.json')
TOKEN_FILE = os.path.join(os.path.dirname(__file__), 'token.json')
CALENDAR_SCOPES = ['https://www.googleapis.com/auth/calendar']


def _get_calendar_service():
    """
    Returns a Google Calendar service using OAuth token if available,
    otherwise falls back to Service Account.
    """
    if os.path.exists(TOKEN_FILE):
        creds = Credentials.from_authorized_user_file(TOKEN_FILE, CALENDAR_SCOPES)
        return build('calendar', 'v3', credentials=creds)
    else:
        creds = service_account.Credentials.from_service_account_file(
            SERVICE_ACCOUNT_FILE, scopes=CALENDAR_SCOPES
        )
        return build('calendar', 'v3', credentials=creds)


def generate_meet_link(date_str: str, time_str: str) -> str:
    """
    Creates a Google Calendar event with a Google Meet conference link.
    Requires token.json (generated by running auth_calendar.py once).
    Returns the Google Meet hangout link, or None if creation fails.
    """
    try:
        service = _get_calendar_service()

        dt_str = f"{date_str} {time_str}"
        dt = datetime.datetime.strptime(dt_str, "%Y-%m-%d %I:%M %p")
        start_time = dt.isoformat()
        end_time = (dt + datetime.timedelta(hours=1)).isoformat()

        event = {
            'summary': 'Rehab 5 Consultation',
            'location': 'Online - Google Meet',
            'description': 'Your scheduled consultation with Rehab 5.',
            'start': {'dateTime': start_time, 'timeZone': 'Asia/Kolkata'},
            'end': {'dateTime': end_time, 'timeZone': 'Asia/Kolkata'},
            'conferenceData': {
                'createRequest': {
                    'requestId': uuid.uuid4().hex,
                    'conferenceSolutionKey': {'type': 'hangoutsMeet'}
                }
            },
        }

        event_result = service.events().insert(
            calendarId='primary',
            body=event,
            conferenceDataVersion=1
        ).execute()

        return event_result.get('hangoutLink')

    except Exception as e:
        print(f"Google Meet event creation failed: {e}")
        return None


def create_calendar_event(date_str: str, time_str: str, meet_link: str) -> bool:
    """
    Creates a plain Google Calendar event with the meet_link in the description.
    Used as fallback.
    """
    try:
        service = _get_calendar_service()

        dt_str = f"{date_str} {time_str}"
        dt = datetime.datetime.strptime(dt_str, "%Y-%m-%d %I:%M %p")
        start_time = dt.isoformat()
        end_time = (dt + datetime.timedelta(hours=1)).isoformat()

        event = {
            'summary': 'Rehab 5 Consultation',
            'location': meet_link,
            'description': f'Join the consultation: {meet_link}',
            'start': {'dateTime': start_time, 'timeZone': 'Asia/Kolkata'},
            'end': {'dateTime': end_time, 'timeZone': 'Asia/Kolkata'},
        }

        service.events().insert(calendarId='primary', body=event).execute()
        return True

    except Exception as e:
        print(f"Calendar event creation failed: {e}")
        return False


def send_email(to_email: str, subject: str, body: str) -> bool:
    password = os.getenv("GMAIL_APP_PASSWORD")
    sender_email = os.getenv("GMAIL_USER")

    if not sender_email or not password:
        print("GMAIL_USER or GMAIL_APP_PASSWORD not found in env")
        return False

    msg = MIMEMultipart("alternative")
    msg['From'] = sender_email
    msg['To'] = to_email
    msg['Subject'] = subject
    msg.attach(MIMEText(body, 'html'))

    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, password)
        server.sendmail(sender_email, to_email, msg.as_string())
        server.quit()
        return True
    except Exception as e:
        print(f"Email failed: {e}")
        return False
